version: '{build}'
branches:
  only:
  - master

#clone_folder: c:\projects\zlib

image:
  #- Visual Studio 2015
  - Visual Studio 2017

configuration:
#  - Release
  - Debug

platform:
  - x64

environment:
  matrix:
  - arch: Win64
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true

# skip unsupported combinations
init:
  - set version=1.2.11
  - set ipath=p:\prj\libs\%APPVEYOR_PROJECT_NAME%\%version%
  - for /f %%v in ('msbuild /version') do set _ver=%%v
  - echo %_ver%
  - for /f "tokens=1,2,3 delims=. " %%a in ("%_ver%") do set v1=%%a&set v2=%%b& set v3=%%c&set mver=%v1%.%v2%.%v3%&set nver=%%a.%%b.%%c
  - echo %mver% %nver%

build_script:
  - cd
  - cmake --version

  - md install
  - cmd: SUBST "P:" install
  - cmd: SUBST 
  - dir p:



  - set
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmd: msbuild /version
  - dir
  - dir p:\ /s
  - cd /d p:\


#artifacts:
#  - path: '**\*.zip'
#  - path: '**\*.lib'


